service: turntable-cloud

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  memory: 768
  stage: dev

package:
  include:
    - lib/**/*.js
  exclude:
    - src/**

functions:
  findSongOnYouTube:
    handler: lib/index.handler