service: turntable-cloud

plugins:
- serverless-plugin-typescript
- serverless-offline

provider:
  name: aws
  region: us-east-2
  stage: dev
  runtime: nodejs8.10

functions:
  findSongOnYouTube:
    runtime: nodejs8.10
    handler: src/index.handler
    memorySize: 768
    events:
    - http:
        method: get
        path: findSongOnYouTube
    