service: turntable-cloud

plugins:
- serverless-plugin-typescript
- serverless-offline

provider:
  name: aws
  region: us-east-2
  stage: dev
  runtime: nodejs12.x

functions:
  findSongOnYouTube:
    handler: src/song-streams.handler
    memorySize: 768
    events:
    - http:
        method: get
        path: findSongOnYouTube
    